name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker ${{vars.REGION}}-docker.pkg.dev
      
      - name: Setup terraform variables
        id: vars
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          region="${{ vars.REGION }}" 
          project_id="${{ vars.PROJECT_ID }}" 
          project_id_number="${{ vars.PROJECT_ID_NUMBER }}"
          db_name="${{ vars.DB_NAME }}"
          github_app_id="${{vars.TF_GITHUB_APP_ID}}"
          

          secrets = {
            db_username = {
              secret_id   = "db-username"
              secret_data = "${{secrets.DB_USERNAME}}"
            }
            db_password = {
              secret_id   = "db-password"
              secret_data = "${{secrets.DB_PASSWORD}}"
            }
            github_access_token = {
              secret_id   = "github_access_token"
              secret_data = "${{secrets.TF_GITHUB_ACCESS_TOKEN}}"
            }
          }
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

      - name: Remove Lock
        run: terraform force-unlock 1726626332541495 --force
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

  notify_destroy:
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - name: Trigger Destroy Workflow
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.TF_GITHUB_ACCESS_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: 'destroy.yml',
              ref: 'main'
            });
