name: Manual Terraform Destroy

on:
  workflow_dispatch:  # This will allow manual trigger

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker ${{vars.REGION}}-docker.pkg.dev
      
      - name: Setup terraform variables
        id: vars
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          region="${{ vars.REGION }}" 
          project_id="${{ vars.PROJECT_ID }}" 
          project_id_number="${{ vars.PROJECT_ID_NUMBER }}"
          db_name="${{ vars.DB_NAME }}"
          github_app_id="${{vars.TF_GITHUB_APP_ID}}"
          

          secrets = {
            db_username = {
              secret_id   = "db-username"
              secret_data = "${{secrets.DB_USERNAME}}"
            }
            db_password = {
              secret_id   = "db-password"
              secret_data = "${{secrets.DB_PASSWORD}}"
            }
            github_access_token = {
              secret_id   = "github_access_token"
              secret_data = "${{secrets.TF_GITHUB_ACCESS_TOKEN}}"
            }
          }
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
